#ifndef DEFINED_H_INCLUDED
#define DEFINED_H_INCLUDED


#define DEBUG 1
#define PRINT_LOCATION 1
#define PRINT_DEBUG_INFO 10
#define PRINT_EACH_POTENTIAL 10
#define PRINT_LOCATION 10
#define PRINT_SPIN 10


#endif // DEFINED_H_INCLUDED
